Review Vignettes
Roche/rtables pull request #440
Opened 2022-11-08 21:51 UTC by edelarua

No updates needed for vignette examples - just some minor formatting/spelling/grammatical fixes for better readability.

Closes #361 

Also added missing `x` argument to `cfun` documentation where needed.

Closes #190

2022-11-10 20:00 UTC, gmbecker requested changes
Needs rebasing on main after merge of the function links PR. In the future please group PRs like this into larger chunks to avoid this issue.

2022-11-10 20:17 UTC, edelarua commented on R/colby_constructors.R
> +#' `cfun` must accept `x` or `df` as its first argument and will receive the subset
I have reverted this change for now and will cover it as part of the new issue.

2022-11-11 07:07 UTC, shajoezhu approved these changes
lgtm! Thanks @edelarua

2022-11-11 07:08 UTC, shajoezhu commented
Hi @gmbecker , I had another look at this. Looks improved. Just wondering what your thoughts are. Can we merge this already please? Thanks

2022-11-11 22:10 UTC, gmbecker approved these changes

2022-11-11 22:10 UTC, merged